use_frameworks!

target 'CollectionManager_Example' do
  pod 'CollectionManager', :path => '../'

  target 'CollectionManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
